title: JSC370 Interactive Visualizations
description: Interactive data visualizations for JSC370 project
baseurl: "/JSC370-project"
url: "https://cyn900.github.io"
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.html
  - data_overview.html
  - eda.html
  - methods.html
  - results.html
  - conclusions.html
exclude:
  - README.md
  - .gitignore
  - .Rproj.user/
  - .Rhistory
  - .DS_Store 