title: JSC370 Interactive Visualizations
description: Interactive data visualizations for JSC370 project
baseurl: "/JSC370-project"
url: "https://cyn900.github.io/JSC370-project/"
markdown: kramdown
theme: minima 